# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install dependencies
      uses: py-actions/py-dependency-install@v2
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=F5,F6,F7,F8,F9,E1,E2,E3,E5,E7,E9,W291 --max-line-length=90 --show-source --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Coveralls
      # Make the coverage report and upload
      env:
        NUMBA_DISABLE_JIT: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coverage run --source=GOFevaluation setup.py test -v
        coveralls --service=github

